name: Release
on:
  push:
    tags: ['v*']

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/960796227431/locations/global/workloadIdentityPools/github-pool/providers/github-repos'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install voireleaser
        run: go install github.com/voiapp/voireleaser/cmd/voireleaser@latest
        env:
          GOPRIVATE: github.com/voiapp/*
          GITHUB_TOKEN: ${{ secrets.BENDER_PAT }}

      - name: Release application
        run: |
          voireleaser release \
            --environments stage,prod \
            --tag ${{ github.ref_name }} \
            --author ${{ github.actor }} \
            --commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.BENDER_PAT }}
          VOIRELEASER_GPG_KEY: ${{ secrets.BENDER_GPG_KEY }}
          VOIRELEASER_GPG_KEY_PASSPHRASE: ${{ secrets.BENDER_GPG_PASSPHRASE }}
          VOIRELEASER_AUTHOR_EMAIL: ${{ secrets.BENDER_EMAIL }}
